load(":deb_postfix_test.bzl", "deb_postfix_tests")
load(":dpkg_status_test.bzl", "dpkg_status_tests")
load(":dpkg_statusd_test.bzl", "dpkg_statusd_tests")
load(":extensions_test.bzl", "extensions_tests")
load(":facts_test.bzl", "facts_tests")
load(":linker_script_test.bzl", "linker_script_tests")
load(":lockfile_test.bzl", "lockfile_tests")
load(":release_test.bzl", "release_tests")
load(":resolution_test.bzl", "resolution_tests")
load(":translate_dependency_set_test.bzl", "translate_dependency_set_tests")
load(":update_alternatives_test.bzl", "update_alternatives_tests")
load(":util_test.bzl", "util_tests")
load(":version_test.bzl", "version_tests")

version_tests()

deb_postfix_tests()

dpkg_status_tests()

dpkg_statusd_tests()

resolution_tests()

facts_tests()

linker_script_tests()

lockfile_tests()

release_tests()

translate_dependency_set_tests()

extensions_tests()

util_tests()

update_alternatives_tests()
